version: '3.3'
services:
  etl-client:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: etl-client
    restart: always
    env_file:
      - ${ENV_FILE}
    ports:
      - ${APP_PORT:-7000}:5000
    networks:
      - public
      
networks:
    public:     
      external: 
        name: quickstart_public
